# Generated by Django 4.1.7 on 2023-12-05 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_chainuser_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chainuser',
            name='referral_code_users_id',
        ),
        migrations.RemoveField(
            model_name='chainuser',
            name='referral_code_users',
        ),
        migrations.AddField(
            model_name='chainuser',
            name='referral_code_users',
            field=models.ManyToManyField(blank=True, related_name='referral_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
