# Generated by Django 4.1.7 on 2023-12-06 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_chainuser_referrer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chainuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='chainuser',
            name='referrer',
        ),
        migrations.AlterField(
            model_name='chainuser',
            name='referral_code_other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
