# Generated by Django 4.1.7 on 2023-12-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_chainuser_referrer_alter_chainuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainuser',
            name='referrer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
