# Generated by Django 4.1.7 on 2023-12-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_chainuser_referrer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chainuser',
            name='referrer_id',
        ),
    ]
