# Generated by Django 4.1.7 on 2023-12-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_product_p_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_id',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
