# Generated by Django 4.1.7 on 2023-12-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_chainuser_email_alter_product_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainuser',
            name='code_users',
            field=models.IntegerField(default=0),
        ),
    ]
