# Generated by Django 4.1.7 on 2023-12-07 12:29

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.CharField(default=myapp.models.generate_random_string, editable=False, max_length=5, unique=True)),
                ('recipient', models.CharField(max_length=255)),
                ('w_amount', models.FloatField()),
                ('ave_balc', models.FloatField()),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
