# Generated by Django 4.1.7 on 2023-12-07 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='acc_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
